### ISSUE TITLE
user crud test 코드 작성

### ISSUE THREAD

**Issue by kimdw0823** [backend-devcourse-team1/JDBCProject#7]
### 💼 작업 설명
user crud test 코드 작성
 
### ✅ To-do

- [ ] MovieMangerImpl.insertUser(User user);
- [ ] MovieMangerImpl.updateUser(User user);
- [ ] MovieMangerImpl.deleteUser(User user);
